name: POI API Publish & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apis/poi/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./apis/poi
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./apis/poi
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./apis/poi
    - name: Create Issue on Build Error
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: POI API Build Failed on master
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Workflow failed for commit ${{github.sha}}
      if: ${{ failure() }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      working-directory: ./apis/poi/web
      with:
        push: true
        tags: openhackzl57ob94acr.azurecr.io/devopsoh/api-poi:${{github.GITHUB_RUN_ID}}
    - name: Create Issue on Package/Publish Error
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: POI API Package/Publish Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Workflow failed for commit ${{github.sha}}
      if: ${{ failure() }}
    # - name: Deploy POI API to Staging Slot
    #   uses: #TODO
    - name: Create Issue on Deploy Error
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: POI API Deploy Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Workflow failed for commit ${{github.sha}}
      if: ${{ failure() }}
      
