name: POI API Publish & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apis/poi/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  
    - name: Start staging 
      id: start_staging
      run: |
        az webapp deployment slot create -g ${{ env.rg-name }} -n ${{ env.app-name }} -s staging  
      env:
          rg-name: openhackzl57ob94rg
          app-name: openhackzl57ob94poi
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
    - name: Build and Publish Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./apis/poi/web
        tags: |
          ${{ secrets.ACR_URL }}/devopsoh/api-poi:${{github.run_id}}
          ${{ secrets.ACR_URL }}/devopsoh/api-poi:latest
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackzl57ob94poi'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_POI }}
        images: '${{ secrets.ACR_URL }}/devopsoh/api-poi:${{github.run_id}}'
        slot-name: staging
    - name:  Swap staging slot into production
      id: slot_swap
      run: |
        az webapp deployment slot swap -g ${{ env.rg-name }} -n ${{ env.app-name }} -s staging
        url=$(az webapp show -g ${{ env.rg-name }} -n ${{ env.app-name }} --query "defaultHostName" -o tsv)
        echo "::set-output name=url::https://openhackzl57ob94poi-staging.azurewebsites.net"
      env:
          rg-name: openhackzl57ob94rg
          app-name: openhackzl57ob94poi
    - name: stop staging 
      id: stop_staging
      run: |
        az webapp deployment slot delete -g ${{ env.rg-name }} -n ${{ env.app-name }} -s staging  
      env:
          rg-name: openhackzl57ob94rg
          app-name: openhackzl57ob94poi
    - name: az cli logout
      run: az logout
      if: ${{ always() }}
           
   
        
