name: POI_API

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'apis/poi/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./apis/poi
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./apis/poi
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./apis/poi
    - name: Create Issue on Error
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Workflow failed for commit ${{github.sha}}
      if: ${{ failure() }}
      
