name: POI API Publish & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apis/poi/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./apis/poi/web
        tags: |
          ${{ secrets.ACR_URL }}/devopsoh/api-poi:${{github.run_id}}
          ${{ secrets.ACR_URL }}/devopsoh/api-poi:latest
      
