name: Trips API Publish & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apis/trips/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
    - name: Build and Publish Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./apis/trips
        tags: |
          ${{ secrets.ACR_URL }}/devopsoh/api-trips:${{github.run_id}}
          ${{ secrets.ACR_URL }}/devopsoh/api-trips:latest
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackzl57ob94trips'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TRIPS }}
        images: '${{ secrets.ACR_URL }}/devopsoh/api-trips:${{github.run_id}}'
        #slot-name: Staging
